# Generated by Django 4.2 on 2023-05-18 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('registrated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
