# Generated by Django 4.2 on 2023-05-15 13:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region=None, verbose_name="Телефон"
            ),
            preserve_default=False,
        ),
    ]
