# Generated by Django 4.2 on 2023-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '044_fill_empty_prices_in_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('RE', 'In restaurant'), ('DE', 'In delivery'), ('CL', 'Closed')], default='NE', max_length=2),
        ),
    ]
