# Generated by Django 4.2 on 2023-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_foodcartapp_status_99d57e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
