# Generated by Django 4.2 on 2023-05-17 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0047_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(blank=True, null=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="registrated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
