# Generated by Django 4.2 on 2023-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('CA', 'Наличными')], default='CA', max_length=2),
        ),
    ]
